### ISSUE TITLE
version 2.27-2 handling |

### ISSUE THREAD

**Issue by toouggy** [rvlenth/lsmeans#9] opened 2017-09-14 03:16 UTC
I have an issue with lsmeans not hadling correctly the | sign.  I tried  lsmeans(model1, list(~ treat, ~ t.nom, ~ treat | t.nom) in the current version and the last treat | t.nom in the list does not work.  The same statement works just fine in version 2.26-3.  Am I doing something wrong?
Please advise.  Thank you

**Comment by rvlenth** [comment] 2017-09-14 16:51
I'm not sure what is wrong, as I can't reproduce the error. For example:
```
> library(lsmeans)
Loading required package: estimability

> packageVersion("lsmeans")
[1] ‘2.27.2’

> warp.lm <- lm(breaks ~ wool*tension, data = warpbreaks)

> lsmeans(warp.lm, list(~wool, ~tension, ~wool|tension, ~tension|wool))
NOTE: Results may be misleading due to involvement in interactions
NOTE: Results may be misleading due to involvement in interactions
$`lsmeans of wool`
 wool   lsmean       SE df lower.CL upper.CL
 A    31.03704 2.105459 48 26.80373 35.27035
 B    25.25926 2.105459 48 21.02595 29.49257

Results are averaged over the levels of: tension 
Confidence level used: 0.95 

$`lsmeans of tension`
 tension   lsmean      SE df lower.CL upper.CL
 L       36.38889 2.57865 48 31.20417 41.57361
 M       26.38889 2.57865 48 21.20417 31.57361
 H       21.66667 2.57865 48 16.48194 26.85139

Results are averaged over the levels of: wool 
Confidence level used: 0.95 

$`lsmeans of wool | tension`
tension = L:
 wool   lsmean       SE df lower.CL upper.CL
 A    44.55556 3.646761 48 37.22325 51.88786
 B    28.22222 3.646761 48 20.88992 35.55453

tension = M:
 wool   lsmean       SE df lower.CL upper.CL
 A    24.00000 3.646761 48 16.66769 31.33231
 B    28.77778 3.646761 48 21.44547 36.11008

tension = H:
 wool   lsmean       SE df lower.CL upper.CL
 A    24.55556 3.646761 48 17.22325 31.88786
 B    18.77778 3.646761 48 11.44547 26.11008

Confidence level used: 0.95 

$`lsmeans of tension | wool`
wool = A:
 tension   lsmean       SE df lower.CL upper.CL
 L       44.55556 3.646761 48 37.22325 51.88786
 M       24.00000 3.646761 48 16.66769 31.33231
 H       24.55556 3.646761 48 17.22325 31.88786

wool = B:
 tension   lsmean       SE df lower.CL upper.CL
 L       28.22222 3.646761 48 20.88992 35.55453
 M       28.77778 3.646761 48 21.44547 36.11008
 H       18.77778 3.646761 48 11.44547 26.11008

Confidence level used: 0.95 
```

I wonder if you exit R and try again, or reinstall **lsmeans**, if that will solve the problem.

**Comment by toouggy** [comment] 2017-09-15 02:39
Hi Russell,

Thank you for the quick answer.  I have not tried with the lm function.  I was using lme from the nlme package.  I will try with lm and see if it is specific for the mixed effects models.  The interesting thing is that the same code works just fine with lsmeans 2.26-3, so it has to be the new version of lsmeans.

I will get back to you.

Thank you.

Paco

**Comment by rvlenth** [comment] 2017-09-15 02:54
If it works for `lm` but not `lme`, it can’t possibly have to do with “|” symbols in the lsmeans specs, because by the time it gets to that point, a reference grid has been created. So *first* check to see that `ref.grid(model)` works correctly and report what it shows.

Also, it’s possible your model has nesting of fixed effects, and if that’s the case, support for that is the big new feature in version 2.27. If, for example, you have treatments nested in groups, you can’t specify `lsmeans(model, ~ group | treatment)` because that doesn’t make sense. The `nested` argument in `ref.grid` (or passed via `lsmeans`) allows the user to override the nesting structures that are found. But the other side if the coin is if you likely will get misleading results.

Russ

**Comment by toouggy** [comment] 2017-09-15 02:59
Hi Russ,

It does not work in the mixed model environment.  How do you explain then that if I run the same exact code, but I install version 2.26-3 it runs just fine?  I have been running that was because I cannot get 2.27-2 to run.

Regards,

Paco

**Comment by rvlenth** [comment] 2017-09-15 03:21
I explain it that there is a lot going on in that one call you show besides the list of formulas. Please run the `ref.grid` call first and see what happens.

Russ

**Comment by toouggy** [comment] 2017-09-15 03:42
Hi Russ,

This is what I get when I run in lsmeans 2.26-3:

> ref.grid(model1)
'ref.grid' object with variables:
    base.mm2.sqrt = 4.3154
    treat = Sham, XXXX, YYYY
    t.nom = 3, 6, 9, 12, 18, 24
    base.tert = Low, MidHigh

And, the statement below works nicely:

> lsm <- lsmeans(model1, list(~ treat, ~ t.nom, ~ treat | t.nom, ~ treat : t.nom : base.tert,
+                             ~ treat | t.nom : base.tert),
+                cov.reduce = FALSE)

Generating the five intems in the list statement.

I installed version 2.27-2.  You were right with respect to the ref.grid.  See below:

> packageVersion("lsmeans")
[1] ‘2.27.2’
> ref.grid(model1)
'ref.grid' object with variables:
    base.mm2.sqrt = 4.3154
    treat = Sham, XXXX, YYYY
    t.nom = 3, 6, 9, 12, 18, 24
    base.tert = Low, MidHigh
Nesting structure:  t.nom %in% treat, base.tert %in% treat

When I run the statement below in the old version, I get a 5 item list as mentioned above.

> lsm <- lsmeans(model1, list(~ treat, ~ t.nom, ~ treat | t.nom, ~ treat : t.nom : base.tert,
+                             ~ treat | t.nom : base.tert),
+                cov.reduce = FALSE)

When I run the same code in version 2.27-2 the lists that have the | do not get generated.  How do I get the output I got in the previous version for the ~ treat | t.nom and  ~ treat | t.nom : base.tert statements like in the other version?  Is there a way to get that output in the new version?

Thank you.

Paco

**Comment by toouggy** [comment] 2017-09-15 04:04
Hi Russ,

I updated the ref.grid to remove the nesting and now I get all the lists with the new version.  I took the liberty of comparing the results with and without the nesting and they seem exactly the same.

Thank you for your support and for a great package.  I think the problem was the detection of the nesting and the results with the old and new version with and without nesting are exactly the same.

Regards,

Paco

**Comment by rvlenth** [comment] 2017-09-15 18:03
The reason `lsmeans` is detecting a nesting structure appears to be because the model has no main effect for `t.nom` or `base.tert` -- only interactions with `treat`. Why is that? It seems to me that the best way to avoid the difficulties you are having is to include those main effects in your model. Without them, the model choice really suggests that these factors don't have effects in their own right, just effects in combination with `treat`. That's what's meant by a nested factor. One can get by computationally by leaving out main effects, but I am an advocate of using models that make *prima facae* sense.

Just to complete the picture with the warp-breaks example, here is another model having a nested structure:
```
> warp.lm.nest <- lm(breaks ~ wool/tension, data = warpbreaks)
> ref.grid(warp.lm.nest)
'emm' object with variables:
    wool = A, B
    tension = L, M, H
Nesting structure:  tension %in% wool
```
This model has predictors `wool` and `tension:wool` (but no main effect for `tension`). The interpretation of such a model is that "low", "medium", and "high" settings are different for wool A than for wool B. Here's the same `lsmeans` call I tested before:
```
> lsmeans(warp.lm.nest, list(~wool, ~tension, ~wool|tension, ~tension|wool))
NOTE: Results may be misleading due to involvement in interactions
$`lsmeans of wool`
  wool   lsmean       SE df lower.CL upper.CL
1    A 31.03704 2.105459 48 26.80373 35.27035
2    B 25.25926 2.105459 48 21.02595 29.49257

$`lsmeans of tension, wool`
  tension wool   lsmean       SE df lower.CL upper.CL
1       L    A 44.55556 3.646761 48 37.22325 51.88786
2       M    A 24.00000 3.646761 48 16.66769 31.33231
3       H    A 24.55556 3.646761 48 17.22325 31.88786
4       L    B 28.22222 3.646761 48 20.88992 35.55453
5       M    B 28.77778 3.646761 48 21.44547 36.11008
6       H    B 18.77778 3.646761 48 11.44547 26.11008

$`lsmeans of tension, wool | `
  tension wool   lsmean       SE df lower.CL upper.CL
1       L    A 44.55556 3.646761 48 37.22325 51.88786
2       M    A 24.00000 3.646761 48 16.66769 31.33231
3       H    A 24.55556 3.646761 48 17.22325 31.88786
4       L    B 28.22222 3.646761 48 20.88992 35.55453
5       M    B 28.77778 3.646761 48 21.44547 36.11008
6       H    B 18.77778 3.646761 48 11.44547 26.11008

$`lsmeans of tension | wool`
  tension wool   lsmean       SE df lower.CL upper.CL
1       L    A 44.55556 3.646761 48 37.22325 51.88786
2       M    A 24.00000 3.646761 48 16.66769 31.33231
3       H    A 24.55556 3.646761 48 17.22325 31.88786
4       L    B 28.22222 3.646761 48 20.88992 35.55453
5       M    B 28.77778 3.646761 48 21.44547 36.11008
6       H    B 18.77778 3.646761 48 11.44547 26.11008
```
In this example, we just keep getting the same table except for the first one, because with the nested structure, it doesn't make sense to vary `tension` without varying its corresponding `wool` value. If you think that `tension` has a constant meaning even though it is nested in `wool`, then you can ignore the nesting structure. The easiest way to do that is
```
lsmeans(warp.lm.nest, list(~wool, ~tension, ~wool|tension, ~tension|wool), 
    nesting = NULL)
````
(results not shown but the same as originally shown for `warp.lm`.)

**Comment by toouggy** [comment] 2017-09-15 19:52
Thank you so much, Russ.  I love your package and use it all the time.  Now all makes sense.

Regards,

Paco

Sent from my iPhone


On Sep 15, 2017, at 11:03, Russell V. Lenth <notifications@github.com<mailto:notifications@github.com>> wrote:


The reason lsmeans is detecting a nesting structure appears to be because the model has no main effect for t.nom or base.tert -- only interactions with treat. Why is that? It seems to me that the best way to avoid the difficulties you are having is to include those main effects in your model. Without them, the model choice really suggests that these factors don't have effects in their own right, just effects in combination with treat. That's what's meant by a nested factor. One can get by computationally by leaving out main effects, but I am an advocate of using models that make prima facae sense.

Just to complete the picture with the warp-breaks example, here is another model having a nested structure:

> warp.lm.nest <- lm(breaks ~ wool/tension, data = warpbreaks)
> ref.grid(warp.lm.nest)
'emm' object with variables:
    wool = A, B
    tension = L, M, H
Nesting structure:  tension %in% wool


This model has predictors wool and tension:wool (but no main effect for tension). The interpretation of such a model is that "low", "medium", and "high" settings are different for wool A than for wool B. Here's the same lsmeans call I tested before:

> lsmeans(warp.lm.nest, list(~wool, ~tension, ~wool|tension, ~tension|wool))
NOTE: Results may be misleading due to involvement in interactions
$`lsmeans of wool`
  wool   lsmean       SE df lower.CL upper.CL
1    A 31.03704 2.105459 48 26.80373 35.27035
2    B 25.25926 2.105459 48 21.02595 29.49257

$`lsmeans of tension, wool`
  tension wool   lsmean       SE df lower.CL upper.CL
1       L    A 44.55556 3.646761 48 37.22325 51.88786
2       M    A 24.00000 3.646761 48 16.66769 31.33231
3       H    A 24.55556 3.646761 48 17.22325 31.88786
4       L    B 28.22222 3.646761 48 20.88992 35.55453
5       M    B 28.77778 3.646761 48 21.44547 36.11008
6       H    B 18.77778 3.646761 48 11.44547 26.11008

$`lsmeans of tension, wool | `
  tension wool   lsmean       SE df lower.CL upper.CL
1       L    A 44.55556 3.646761 48 37.22325 51.88786
2       M    A 24.00000 3.646761 48 16.66769 31.33231
3       H    A 24.55556 3.646761 48 17.22325 31.88786
4       L    B 28.22222 3.646761 48 20.88992 35.55453
5       M    B 28.77778 3.646761 48 21.44547 36.11008
6       H    B 18.77778 3.646761 48 11.44547 26.11008

$`lsmeans of tension | wool`
  tension wool   lsmean       SE df lower.CL upper.CL
1       L    A 44.55556 3.646761 48 37.22325 51.88786
2       M    A 24.00000 3.646761 48 16.66769 31.33231
3       H    A 24.55556 3.646761 48 17.22325 31.88786
4       L    B 28.22222 3.646761 48 20.88992 35.55453
5       M    B 28.77778 3.646761 48 21.44547 36.11008
6       H    B 18.77778 3.646761 48 11.44547 26.11008


In this example, we just keep getting the same table except for the first one, because with the nested structure, it doesn't make sense to vary tension without varying its corresponding wool value. If you think that tension has a constant meaning even though it is nested in wool, then you can ignore the nesting structure. The easiest way to do that is

lsmeans(warp.lm.nest, list(~wool, ~tension, ~wool|tension, ~tension|wool),
    nesting = NULL)


(results not shown but the same as originally shown for warp.lm.)

**Comment by rvlenth** [comment] 2017-09-15 21:36
Thanks. I will close this.

**Comment by rvlenth** [comment] 2017-09-15 21:38
I will close this now. I edited the quotes off all the e-mails so it's easier to see the exchange.

**Closed as completed** 2017-09-15 21:38 UTC
