### ISSUE TITLE
Trying to understand Warning Message

### ISSUE THREAD

**Issue by aranglancy** [rvlenth/lsmeans#11] opened 2017-10-26 15:03 UTC
I'm trying to use lsmeans to generate predicted values and CIs for a logistic model (glm). I keep getting this warning message:

> Warning message:
> Function call in data or subset: ref.grid/lsmeans results may be inconsistent

As far as I can tell there is nothing wrong, but the warning doesn't make sense to me so I can't be sure. Can someone explain in more detail what exactly the warning is warning about how to check if there is an issue?

Thanks.

**Comment by rvlenth** [comment] 2017-10-26 17:04
I'll explain why the warning exists, and maybe that'll help. I was getting strange bugs reported by a user who fit a model something like this:
```
mymod <- glm(cbind(succ, fail) ~ treat + time, family = binomial, 
    data = mydata, subset = sample(1:72, 36))
lsmeans(mymod, "treat")
```
... and the user was puzzled because he ran this twice and got different results.

The reason is because `lsmeans()` uses the model call to reconstruct the dataset, in order to determine factor levels, means of covariates, etc. But in this case the model call includes obtaining a random subset of the data, and a *new* random subset is produced when the data are reconstructed. That makes the results not reflect what was used in the fitted model. If, for example, the user did this to simulate results from `lsmeans()`, the simulation will be wrong.

In order to guard against this kind of error, I have code that checks the model call, and if there is a function call in `data` or `subset`, I issue a warning.

So -- you have nothing to worry about as long as your model will be exactly the same if it is re-fitted with the same command. If that isn't the case, then that explains why you get the warning.

If you have any suggestions on how to make the warning clearer without printing out a long paragraph, I'm all ears!

**Comment by rvlenth** [comment] 2017-10-26 17:05
PS -- You might want to switch to the **emmeans** package, which is the successor to **lsmeans** and will be where all future developments will take place. (It will issue the same warning...)

**Comment by aranglancy** [comment] 2017-10-26 17:21
This is extremely helpful and makes perfect sense.  Thanks also for the super quick response! That was awesome. As for how to reword, I'm not really sure. Maybe something like:

> Function call in data or subset: ref.grid/lsmeans results may be inconsistent over repeated function calls

And I will switch to emmeans. Thanks again!

**Comment by rvlenth** [comment] 2017-10-31 18:24
Just an update on this. In the Oct 31 **emmeans** push to github, I changed the code where it checks and produces this warning. Instead, under those conditions, it reproduces the data twice and compares the results. If it produces identical data, it goes on; else it throws an error (not just a warning) with a clearer message:
```
Error in recover_data.call(fcall, delete.response(terms(object)), object$na.action,  : 
  Data appear to be randomized -- cannot consistently recover the data
Move the randomization outside of the model-fitting call.
```

PS -- I'm going to close this issue on the **lsmeans** site, even though I am not making the same correction to **lsmeans**

**Closed as completed** 2017-10-31 18:25 UTC
